Repository elixirs/faker, pull requests merged in 2019-10, with the labels that each got.

#286 Add over 800 pokemon names
  CHANGELOG.md
  lib/faker/pokemon.ex
  lib/faker/pokemon/en.ex
Labels: Update/add locales

#297 Fix vehicle model with make
  CHANGELOG.md
  lib/faker/vehicle.ex
Labels: bug

#304 Add Faker.Pokemon.It.name()
  CHANGELOG.md
  lib/faker/pokemon/it.ex
  test/faker/pokemon_test.exs
Labels: enhancement

#301 Add Faker.Pokemon.It.location()
  CHANGELOG.md
  USAGE.md
  lib/faker/pokemon/it.ex
Labels: enhancement
